---
title: "Carbon Dioxide Concentrations at Mona Loa Observatory"
author: "Adam M. Wilson"
toc: true
format:
  html: default # Website
  gfm: default  # Github Flavored Markdown
  pptx: default # Powerpoint
  docx: default # MS Word
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(magick)
```

```{r import_data, results='hide',message=FALSE, echo=F}

drop_outliers <- function(x) {
   x2=na.omit(x) #remove observations with missing values
   return(x) #return filtered dataset 
}
   
# get data
data=read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt",
                col_names = c("year","mean","unc"),
                comment = "#") %>% 
  drop_outliers()

```

# Annual Mean Carbon Dioxide Concentrations 1959-Present

```{r pressure, echo=FALSE}
ggplot(data,aes(x=year,y=mean))+
         geom_line(col="red",linewidth=2)+
  ylab("Mauna Loa Annual Mean CO_2 (ppm)")+
  xlab("Year")
```

# Top Five Annual Mean Carbon Dioxide Concentrations at Mona Loa

```{r, echo=F, warning=FALSE}
 ```

```{r, eval=F, echo=F}
rmarkdown::render("CS_08_template/CS_08_template.Rmd",output_format = "all")
```
